### ISSUE TITLE
Syntax error on "Contribute" page

### ISSUE THREAD

**Issue by KeronCyst** [HandBrake/HandBrake-docs#102]
On https://handbrake.fr/docs/en/1.3.0/contributing/contribute.html

It says "a create pull request" instead of "create a pull request."

I've been trying to figure out for the entire past half-hour how to fix this myself on my Windows 10, but I can't find a single step-by-step tutorial online which _doesn't_ have a bunch of hidden, unexplained steps inside step 1 or 2.

**Comment by bradleysepos** [comment]
Thanks for your interest in helping. The contributing doc for this repository is more detailed and may help fill in the blanks: https://github.com/HandBrake/HandBrake-docs/blob/master/CONTRIBUTING.markdown

**Comment by KeronCyst** [comment]
Yes, I tried reading that before giving up and posting here. That guide was extremely confusing to me. Let's pretend I don't know code. That's basically where I'm at. It says:

"Run build-tools from the main directory"

What "main directory?" I know nothing.

**Comment by bradleysepos** [comment]
I'm not sure it will be feasible to explain Bash, binary executables running under Linux Subsystem for Windows, command line git, etc. here. 😞

You might have better luck attempting to edit the files (fork the repo first) and submit changes directly via the GitHub website. I'm sure they have some guides for that. Otherwise this may better fall under the, "thanks for the heads up, we'll fix the typo" category. Which is absolutely okay and appreciated. 😸

**Comment by bradleysepos** [comment]
This is fixed and will be live the next time the documentation is generated and published (usually within 24 hours). Thanks for the report! 😸
