### ISSUE TITLE
Unable to build tools

### ISSUE THREAD

**Issue by chrisfinazzo** [HandBrake/HandBrake-docs#11]
I am new to the project and getting set up. I cloned the project according to the instructions, sync'd it to my account and added the submodules (`git submodule init` and `git submodule update`), however, I am unable to run any of the build scripts (e.g, `build-tools`, `marsh build`). This may be a side effect of the changes introduced in 1.0 and the docs themselves lagging behind, but it may be that I just missed a step.

<img width="942" alt="screen shot 2016-12-30 at 10 42 34 am" src="https://cloud.githubusercontent.com/assets/1534882/21567768/b87ae6b2-ce7c-11e6-9f7e-d5b7f27ae092.png">

**Comment by bradleysepos** [comment]
Hi Chris,

Do you have development tools set up for building software? `cd tools/discount && ./configure` and paste the output here.

`marsh` is a script in the root directory, so you'll need to prefix it with the path like the other script (`./marsh`).

**Comment by chrisfinazzo** [comment]
The output is as follows:

```
cd tools/discount
$ ./configure.sh
Configuring for [markdown]
Looking for cpp (/usr/bin/cpp) ok
looking for install (/usr/bin/install)
checking the C compiler (cc) yuck, you're using clang
looking for ar (/usr/bin/ar)
looking for ranlib (/usr/bin/ranlib)
looking for pkg-config (/usr/local/bin/pkg-config)
checking for "volatile" keyword (found)
checking for "const" keyword (found)
Checking for "inline" keyword (found)
defining WORD & DWORD scalar types
looking for a reentrant basename (found)
looking for header libgen.h (found)
looking for header stdlib.h (found)
looking for the alloca function (found in alloca.h)
looking for header pwd.h (found)
looking for the getpwuid function (found)
looking for the srandom function (found)
looking for the bzero function (found)
looking for the random function (found)
looking for the strcasecmp function (found)
looking for the strncasecmp function (found)
looking for the fchdir function (found)
looking for header malloc.h (not found)
looking for find (/usr/bin/find)
looking for "ln -s" (/bin/ln)
looking for ar (/usr/bin/ar)
looking for ranlib (/usr/bin/ranlib)
looking for sed (/usr/bin/sed)
generating Makefile
generating version.c
generating mkdio.h
generating libmarkdown.pc
```

**Comment by bradleysepos** [comment]
Hmm, that seems fine. Try running `make` and see if there's an error.

**Comment by chrisfinazzo** [comment]
<img width="942" alt="screen shot 2016-12-30 at 6 22 31 pm" src="https://cloud.githubusercontent.com/assets/1534882/21574315/bf383044-cebe-11e6-929e-63a2fda831bf.png">

**Comment by bradleysepos** [comment]
Oops, sorry. Run `make` from the discount directory, where you ran the configure script.

**Comment by bradleysepos** [comment]
Looks like bash isn't escaping a variable that looks to be escaped to me, so I'll try to fix that in `marsh` too.

**Comment by bradleysepos** [comment]
I pushed a fix for `marsh`. Looks like one of the commands was failing on special characters (in this case, a space in the directory name, oof).

Unfortunately, it looks like `discount`'s configure script really doesn't like spaces in the name. I'll see what if anything we can do about this.

**Comment by bradleysepos** [comment]
I've opened https://github.com/Orc/discount/issues/158 regarding the issue building from our script.

Aside, it's not necessary to build a special version of discount anymore. Later versions allow markdown settings configuration at run time instead of build time. I'll probably move away from including the `build-tools` script in the future.

You can manually clone, build, and install discount markdown system-wide using the following instructions. Just make sure there are no spaces in any of the directory names, to work around the known issue.

```
git clone https://github.com/Orc/discount.git && cd discount
./configure.sh --prefix=/usr/local
make
sudo make install
```

This will install `markdown` at `/usr/local/bin`. `marsh` should find and use it automatically.

Thanks for reporting, and sorry for all the trouble. If you have any other questions, don't hesitate to ask.

**Comment by bradleysepos** [comment]
I've updated the submodule to use latest discount, which fixes the issue with spaces in the directory path. https://github.com/HandBrake/HandBrake-docs/commit/d205b1c9367def6aea383dd17ce7a4e901f0a62c adds another fix for the `build-tools` script. All issues discussed here should be resolved.

Note that if you build discount using the `build-tools` script, you'll want to tell `marsh` where the `markdown` program is like this:

    ./marsh build --markdown=tools/local/bin/markdown

If you build and install discount system-wide (so that typing `which markdown` shows `/usr/local/bin/markdown` or similar), `marsh` will find it automatically.

I promise this isn't as complicated as these bugs would make it seem! Let me know if you run across any other issues.

**Comment by chrisfinazzo** [comment]
I'll probably trash the directory, stash my changes elsewhere, and start with a clean slate. Thanks for turning around a fix for this so quickly.
