### ISSUE TITLE
HandBrake included in Debian and Ubuntu package sources(?)

### ISSUE THREAD

**Issue by Lukas2112** [HandBrake/HandBrake-docs#165]
It seems that Handbrake can now be installed natively via the normal package sources, at least under Debian (see https://packages.debian.org/bullseye/handbrake), but apparently also under Ubuntu 20.04. LTS (my current distro). 

In this respect, if this can be verified, we should consider adapting the installation instructions for Debian and Ubuntu.

**Comment by sr55** [comment]
These are not official builds and are not supported by the HandBrake Team.

Please see:  https://handbrake.fr/docs/en/1.5.0/get-handbrake/where-to-get-handbrake.html  "Warning about broken third-party builds"

**Comment by Lukas2112** [comment]
> These are not official builds and are not supported by the HandBrake Team.
> 
> Please see: https://handbrake.fr/docs/en/1.5.0/get-handbrake/where-to-get-handbrake.html "Warning about broken third-party builds"

Would it be worth considering whether it would be worth the effort to have Handbrake fully functional in the official Debian 12 package sources?

**Comment by bradleysepos** [comment]
HandBrake has been around nearly 20 years, perhaps 15 on Linux, give or take. We've encountered smart, thoughtful packagers who do a great job and ship proper builds and/or build recipes. We've also encountered unreasonable, irresponsible packagers who cite rules about static dependencies (no problem, don't ship HandBrake), but don't seem to have any problem at all shipping their known broken modifications. Probably because we get the bug reports, not them. Then there are certain users (thankfully few) who on occasion come by just to argue with us without attempting to understand, because they implicitly and completely trust their repo's infallible packagers. Some people simply cannot fathom a major distro could do something in an illogical and incorrect manner.

We made more efforts in the early days. Some of us went out of our way to file bugs or contact package maintainers directly. Most threads and discussions ended up dead ends, leaving us shaking our heads.

All this to say, we're not making any proactive efforts in that direction these days. Our team is small and time is limited. Considering most existing broken packages have been that way for a decade or more, we feel our time is better spent developing HandBrake itself.

Perhaps this comes off a bit sobering or even pessimistic. It is unfortunately realistic, in our experience.

FWIW, HandBrake has been in the Debian Multimedia repo for many years. I'm not sure whether that needed to be specially enabled in the past; it's been awhile since I looked at it. Unfortunately, this is one of the original and longest running broken builds in HandBrake history.

**Comment by Lukas2112** [comment]
First of all, thank you for your very detailed and comprehensible answer! If I came across as demanding in any way in my message, I would like to apologise to the persons concerned. In any case, my message was not intended as such.

In fact, I was and am aware of the fact that there is a small team and little time available and initially just wanted to ask in principle what the project's position is on this. 

In view of what you describe, it is of course understandable why it is handled the way it is. Could people like me, for example, somehow support the HandBrake project?

In the default Debian installation, only the "main" repository is loaded - if that is not put in there, it would have to be proactively activated by $User.

**Comment by bradleysepos** [comment]
You're welcome. Thanks for your interest and concern for the project. I certainly do not group you in with the aforementioned. 😸 Rather, I simply wanted to give a thoughtful and complete response to hopefully indicate while we do care, past efforts have been mostly fruitless, and it's not something we focus on these days.

We've listed a few ways people can contribute in the docs (https://handbrake.fr/docs/en/latest/contributing/contribute.html) and the Linux UI is in the `gtk` directory, if you feel like exploring.

I noticed the Debian package is maintained by Debian Multimedia Maintainers but am not sure whether that's the same as what is/was the Debian Multimedia repository from yesteryear.
