### ISSUE TITLE
How does encoding speed affect file size? 

### ISSUE THREAD

**Issue by jtheletter** [HandBrake/HandBrake-docs#23]
The prose of this article doesn't mention how encoding speed of general presets affects final file size: 

https://handbrake.fr/docs/en/latest/technical/official-presets.html

But the chart in that article seems to indicate that faster speeds should always make for a smaller file, and slower makes larger. 

Is this correct? I'd expect the choice of quality (1080p vs 720p etc) would determine larger vs smaller file sizes. Why should a slow (deliberate? careful?) pass not make for a smaller (more well configured?) file? 

Thank you.

**Comment by bradleysepos** [comment]
Ah, thanks for pointing that out. I can see where the confusion comes from.

In short, the faster presets usually would make for larger files at the same quality/crf setting. But in fact, we lower the quality for the faster presets, which both speeds up the encode and makes for smaller files, since more bits are thrown away.

So, perhaps we should include the RF in the table or otherwise clarify this.

**Comment by bradleysepos** [comment]
Added in https://github.com/HandBrake/HandBrake-docs/commit/39d48999fd72b28a10b98633731b749099d02774 and subsequent commits, see https://handbrake.fr/docs/en/latest/technical/performance.html

**Comment by Thunderchild64** [comment]
I am a little confused. why is there a separate quality setting RF and encoder speed? It would seem that encoder speed and quality setting are a combined quality setting. Should these not be rolled into one?
