### ISSUE TITLE
4K TV presets?

### ISSUE THREAD

**Issue by jimlynnjulian** [HandBrake/HandBrake-docs#87]
I read the section on presets and was surprised to find no settings specifically for 4K (8K?) TVs.
Are any of the existing presets suitable?

**Comment by bradleysepos** [comment]
Try the Apple or Roku 2160p 4K presets under Devices.

Unfortunately, while H.265/HEVC and 4K support has really started to penetrate the market, different manufacturers support different container formats. Apple, for instance, supports MP4, while Roku supports MKV. TVs can be just as disparate. As such, we haven't created a general purpose 4K preset because none could exist and be widely compatible. For now, 4K presets for popular devices seems like the best solution.

If you have further questions, feel free to ask on our [forums](https://forum.handbrake.fr/) or the [main project repo](https://github.com/HandBrake).
